language: r
r:
- release
- devel
os:
- linux
# - osx
matrix:
  exclude:
  - r: devel
    os: osx
sudo: false
cache: packages
before_install:
- if [ "${TRAVIS_OS_NAME}" == "osx" ]; then sudo tlmgr install comment multirow; export _R_CHECK_FORCE_SUGGESTS_=FALSE; fi
r_github_packages:
- statnet/statnet.common-private
- statnet/network-private
- statnet/ergm-private@dev
- statnet/ergm.count-private@dev
- statnet/ergm.multi-private@ergm.multi
addons:
  apt:
    packages:
      - r-cran-rmpi
warnings_are_errors: false
r_build_args: --no-build-vignettes
r_check_args: --no-vignettes
