language: r
r:
- release
- devel
os:
- linux
- osx
- windows
matrix:
  exclude:
  - r: devel
    os: osx
  - r: devel
    os: windows
sudo: false
cache: packages
before_install:
- if [ "${TRAVIS_OS_NAME}" == "osx" ]; then sudo tlmgr install comment multirow; export _R_CHECK_FORCE_SUGGESTS_=FALSE; fi
r_github_packages:
- statnet/statnet.common
- statnet/network
- statnet/ergm
- statnet/ergm.count
- statnet/tergm
addons:
  apt:
    packages:
      - r-cran-rmpi
warnings_are_errors: false
r_build_args: --no-build-vignettes
r_check_args: --no-vignettes
