language: r
r:
- release
- devel
sudo: false
cache: packages
r_github_packages:
- statnet/statnet.common
- statnet/network
- statnet/ergm
- statnet/ergm.count
addons:
  apt:
    packages:
      - r-cran-rmpi
warnings_are_errors: false